server:
  port: 8081
  tomcat: 
    uri-encoding: UTF-8
spring:
    # 环境 dev
    profiles: 
        active: dev
    application:
        name: zjtzsw-ssm
    # jackson时间格式化
    jackson:
        time-zone: GMT+8
        date-format: yyyy-MM-dd HH:mm:ss
    http:
        multipart:
          maxFileSize: 50MB
          maxRequestSize: 100MB
    session:
        store-type:none
  
# Mybatis配置
mybatis:
    mapperLocations: classpath:mapper/**/*.xml
    configLocation: classpath:mybatis.xml
    
pagehelper:
    helperDialect: oracle
    reasonable: true
    supportMethodsArguments: true
    params: count=countSql
sso:
  url: http://127.0.0.1:8081/sso/index
  welcomeurl: http://127.0.0.1:8081/demo/index
  passUrl: /sso/*